### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by maurer** [souffle-lang/benchmarks#1]
I'm looking to benchmark my own datalog implementation, and am wondering where the benchmark `.dl` files came from, or if they are original work for this project, what license you are offering them under.

**Comment by psubotic** [comment]
Hi, they are licensed under UPL. They will be part of a benchmark paper we are working on ATM. We would be more than happy to send you an early draft for your interest/future work. Also this benchmark suite is evolving so you might want to check up on it in the next months.

**Comment by psubotic** [comment]
Also, if you would like to contribute to the benchmark suite/paper we are more than happy to collaborate. Perhaps we can set up a Skype with myself or Bernhrd Scholz @b-scholz  ?

**Comment by b-scholz** [comment]
Sure - let's talk. Please email me. My email is Bernhard.Scholz@sydney.edu.au
